# Generated by Django 5.1.6 on 2026-08-30 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_code', models.CharField(choices=[('not_verified', 'I made payment but it was not verified'), ('not_received', 'I have not received my money'), ('wrong_amount', 'Wrong amount received'), ('wrong_details', 'Wrong payment details'), ('technical', 'Technical problem'), ('other', 'Something else')], max_length=40)),
                ('detail', models.TextField(blank=True)),
                ('state', models.CharField(default='open', max_length=20)),
                ('resolution', models.CharField(blank=True, choices=[('closed', 'Payout confirmed, case closed'), ('resent', 'Payout sent again'), ('refunded', 'Customer refunded'), ('escalated', 'Escalated')], max_length=40)),
                ('resolution_note', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='transactions.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
