# Generated by Django 5.1.6 on 2026-08-30 14:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RateProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=30, unique=True)),
                ('label', models.CharField(max_length=60)),
                ('is_active', models.BooleanField(default=False)),
                ('refresh_seconds', models.PositiveIntegerField(default=60)),
                ('hold_seconds', models.PositiveIntegerField(default=60)),
                ('markup_bps', models.PositiveIntegerField(default=25, help_text='Basis points. 25 = 0.25%')),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='RateSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_rate', models.DecimalField(decimal_places=10, max_digits=20)),
                ('effective_rate', models.DecimalField(decimal_places=10, max_digits=20)),
                ('fetched_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='geo.currency')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='rates.rateprovider')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='geo.currency')),
            ],
            options={
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=32, unique=True)),
                ('direction', models.CharField(max_length=10)),
                ('send_amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('converted_amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('fee_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fee_amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('receive_amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('rate_used', models.DecimalField(decimal_places=10, max_digits=20)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('corridor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='geo.corridor')),
                ('receive_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='geo.currency')),
                ('send_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='geo.currency')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to=settings.AUTH_USER_MODEL)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='rates.ratesnapshot')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ratesnapshot',
            index=models.Index(fields=['base', 'quote', '-fetched_at'], name='rates_rates_base_id_a658d3_idx'),
        ),
    ]
