# Generated by Django 5.1.6 on 2026-08-30 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=40, unique=True)),
                ('label', models.CharField(max_length=60)),
                ('side', models.CharField(choices=[('collect', 'Collect'), ('payout', 'Payout')], max_length=10)),
                ('icon', models.CharField(default='payments', help_text='Material Symbols Rounded name', max_length=40)),
                ('note', models.CharField(blank=True, help_text='Instant, NEFT/RTGS, CBDC', max_length=40)),
                ('is_enabled', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='geo.country')),
            ],
            options={
                'ordering': ['country__sort_order', 'sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='PaymentInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fields', models.JSONField(blank=True, default=dict)),
                ('body', models.TextField(blank=True, help_text='Free text, shown under the fields')),
                ('qr_key', models.CharField(blank=True, max_length=255)),
                ('reference_format', models.CharField(default='NKP-{order}', max_length=40)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('method', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instruction', to='payments.paymentmethod')),
            ],
        ),
    ]
