# Generated by Django 5.1.6 on 2026-08-30 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datasets', models.JSONField(default=list)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('fmt', models.CharField(default='csv', max_length=8)),
                ('state', models.CharField(default='queued', max_length=12)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('storage_key', models.CharField(blank=True, max_length=255)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_index=True, max_length=200)),
                ('session_key', models.CharField(db_index=True, max_length=64)),
                ('referrer', models.CharField(blank=True, max_length=300)),
                ('source', models.CharField(blank=True, max_length=40)),
                ('device', models.CharField(default='desktop', max_length=12)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['path', '-at'], name='analytics_p_path_40cc63_idx')],
            },
        ),
    ]
