# Generated by Django 5.1.6 on 2026-08-30 14:35

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(blank=True, help_text='Blank applies to both', max_length=10)),
                ('percent', models.DecimalField(decimal_places=2, default=Decimal('6.00'), max_digits=5)),
                ('min_fee', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('max_fee', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('corridor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_rules', to='geo.corridor')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_rules', to='geo.country')),
                ('fee_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='geo.currency')),
            ],
            options={
                'ordering': ['-valid_from'],
            },
        ),
        migrations.CreateModel(
            name='PlatformSetting',
            fields=[
                ('key', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('value', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransferLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(max_length=10)),
                ('minimum', models.DecimalField(decimal_places=4, max_digits=18)),
                ('maximum', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('daily_maximum', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('monthly_maximum', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('manual_review_above', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('corridor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limits', to='geo.corridor')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='geo.currency')),
            ],
            options={
                'unique_together': {('corridor', 'direction')},
            },
        ),
    ]
