# Generated by Django 5.1.6 on 2026-09-07 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='id_document_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='id_document_type',
            field=models.CharField(blank=True, choices=[('passport', 'Passport'), ('national_id', 'National identity card'), ('residence_permit', 'Residence permit'), ('drivers_licence', 'Driving licence')], max_length=24),
        ),
        migrations.AddField(
            model_name='profile',
            name='id_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_reminder_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='reminders_sent',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_state',
            field=models.CharField(choices=[('unverified', 'Nothing submitted'), ('pending', 'Waiting on the desk'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='unverified', max_length=12),
        ),
        migrations.AddField(
            model_name='profile',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
