# Generated by Django 5.1.6 on 2026-09-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_id_document_key_profile_id_document_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_reminders_sent',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_email_reminder_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
