# Generated by Django 5.1.6 on 2026-08-31 02:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(unique=True)),
                ('reason', models.CharField(max_length=280)),
                ('kind', models.CharField(blank=True, choices=[('login_failed', 'Failed login'), ('login_locked', 'Account locked after repeated failures'), ('login_new_device', 'Sign-in from a new device'), ('password_reset_abuse', 'Repeated password reset requests'), ('registration_abuse', 'Repeated sign-ups from one address'), ('rate_limited', 'Rate limit reached'), ('csrf_failed', 'CSRF check failed'), ('permission_denied', 'Permission denied'), ('injection_probe', 'Injection probe'), ('traversal_probe', 'Path traversal probe'), ('scanner', 'Automated scanner'), ('bad_upload', 'Rejected upload'), ('idempotency_replay', 'Duplicate request replayed'), ('quote_abuse', 'Excessive quote requests'), ('enumeration', 'Account or reference enumeration'), ('admin_action_denied', 'Desk action refused'), ('blocked', 'Request from a blocked address')], max_length=32)),
                ('hits', models.PositiveIntegerField(default=1)),
                ('is_automatic', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'blocked addresses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200)),
                ('scope', models.CharField(default='', max_length=100)),
                ('method', models.CharField(max_length=8)),
                ('path', models.CharField(max_length=300)),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('response_body', models.JSONField(blank=True, null=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['-created_at'], name='security_id_created_d9c7d5_idx')],
                'unique_together': {('key', 'scope')},
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('login_failed', 'Failed login'), ('login_locked', 'Account locked after repeated failures'), ('login_new_device', 'Sign-in from a new device'), ('password_reset_abuse', 'Repeated password reset requests'), ('registration_abuse', 'Repeated sign-ups from one address'), ('rate_limited', 'Rate limit reached'), ('csrf_failed', 'CSRF check failed'), ('permission_denied', 'Permission denied'), ('injection_probe', 'Injection probe'), ('traversal_probe', 'Path traversal probe'), ('scanner', 'Automated scanner'), ('bad_upload', 'Rejected upload'), ('idempotency_replay', 'Duplicate request replayed'), ('quote_abuse', 'Excessive quote requests'), ('enumeration', 'Account or reference enumeration'), ('admin_action_denied', 'Desk action refused'), ('blocked', 'Request from a blocked address')], db_index=True, max_length=32)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='low', max_length=10)),
                ('summary', models.CharField(max_length=280)),
                ('ip', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('identifier', models.CharField(blank=True, db_index=True, max_length=190)),
                ('method', models.CharField(blank=True, max_length=8)),
                ('path', models.CharField(blank=True, max_length=300)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referer', models.CharField(blank=True, max_length=300)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-at'],
                'indexes': [models.Index(fields=['ip', '-at'], name='security_se_ip_dcabed_idx'), models.Index(fields=['kind', '-at'], name='security_se_kind_47522c_idx'), models.Index(fields=['severity', '-at'], name='security_se_severit_014e0f_idx')],
            },
        ),
    ]
