# Generated by Django 5.1.6 on 2026-08-30 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('symbol', models.CharField(max_length=6)),
                ('minor_units', models.PositiveSmallIntegerField(default=2)),
            ],
            options={
                'verbose_name_plural': 'currencies',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('iso2', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('dial_code', models.CharField(max_length=6)),
                ('flag_emoji', models.CharField(blank=True, max_length=8)),
                ('is_enabled', models.BooleanField(default=False)),
                ('is_origin', models.BooleanField(default=False)),
                ('is_destination', models.BooleanField(default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='countries', to='geo.currency')),
            ],
            options={
                'verbose_name_plural': 'countries',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Corridor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corridors_out', to='geo.country')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corridors_in', to='geo.country')),
            ],
            options={
                'ordering': ['source__sort_order', 'target__sort_order'],
                'unique_together': {('source', 'target')},
            },
        ),
    ]
