# Generated by Django 5.1.6 on 2026-08-30 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
        ('payments', '0001_initial'),
        ('rates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionCounter',
            fields=[
                ('day', models.DateField(primary_key=True, serialize=False)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=24, unique=True)),
                ('direction', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('order_created', 'Order created'), ('awaiting_payment', 'Awaiting payment'), ('proof_submitted', 'Payment proof submitted'), ('payment_verification', 'Payment verification'), ('payment_confirmed', 'Payment confirmed'), ('payout_processing', 'Payout processing'), ('payout_sent', 'Payout sent'), ('awaiting_confirmation', 'Awaiting customer confirmation'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected'), ('disputed', 'Disputed'), ('refund_pending', 'Refund / correction pending')], db_index=True, default='order_created', max_length=30)),
                ('rate_used', models.DecimalField(decimal_places=10, max_digits=20)),
                ('fee_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('send_amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('converted_amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('fee_amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('receive_amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('recipient_name', models.CharField(blank=True, max_length=160)),
                ('recipient_number', models.CharField(blank=True, max_length=32)),
                ('recipient_details', models.JSONField(blank=True, default=dict)),
                ('needs_manual_review', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_reason', models.TextField(blank=True)),
                ('payout_sent_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('collect_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='payments.paymentmethod')),
                ('corridor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='geo.corridor')),
                ('payout_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='payments.paymentmethod')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rates.quote')),
                ('receive_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='geo.currency')),
                ('send_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='geo.currency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=30)),
                ('to_status', models.CharField(max_length=30)),
                ('is_system', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='transactions.transaction')),
            ],
            options={
                'verbose_name_plural': 'status history',
                'ordering': ['at'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=24, unique=True)),
                ('pdf_key', models.CharField(blank=True, max_length=255)),
                ('snapshot', models.JSONField(default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='transactions.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_from_desk', models.BooleanField(default=False)),
                ('kind', models.CharField(choices=[('text', 'Text'), ('system_notice', 'System notice'), ('system_instructions', 'Payment instructions'), ('attachment', 'Attachment'), ('action', 'Action')], default='text', max_length=24)),
                ('body', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='transactions.transaction')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_key', models.CharField(max_length=255)),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('size_bytes', models.PositiveIntegerField()),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('is_payment_proof', models.BooleanField(default=False)),
                ('scanned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='transactions.message')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='transactions.transaction')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', '-created_at'], name='transaction_user_id_386a11_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status', '-created_at'], name='transaction_status_4b1739_idx'),
        ),
    ]
