# Generated by Django 5.1.6 on 2026-08-31 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='purged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
